name: Rspec and lint
on:
  push:
  workflow_dispatch:
      inputs:
        experimental:
          description: 'Is this an experimental version'
          required: true
          type: boolean
          default: true
        runs-on:
          description: 'Operating System'
          required: true
          type: choice
          default: 'ubuntu-latest'
          options: ['ubuntu-20.04','ubuntu-latest']
        ruby-version:
          description: 'Ruby Version'
          required: true
          type: choice
          default: '3.3'
          options: ['2.7','3.0','3.1','3.2','3.3','3.4','4.0']
jobs:
  call-build-and-test-on-manual:
    if: github.event_name == 'workflow_dispatch'
    name: Experimental Ruby ${{ inputs.ruby-version }} specs and lint
    uses: ./.github/workflows/build-test-workflow.yml
    with:
      ruby-version: ${{ inputs.ruby-version }}
      experimental: ${{ inputs.experimental }}
      runs-on: ${{ inputs.runs-on }}
      mongo-version: 6
    secrets:
      github-token: ${{ secrets._ORG_GITHUB_TOKEN }}

  call-build-and-test-on-push:
    if: github.event_name == 'push'
    name: Ruby ${{ matrix.ruby-version }} specs and lint
    strategy:
      fail-fast: true
      matrix:
        ruby-version: ['2.7','3.0','3.1','3.2']
        experimental: [false]
        runs-on: [ubuntu-20.04]
    uses: ./.github/workflows/build-test-workflow.yml
    with:
      ruby-version: ${{ matrix.ruby-version }}
      experimental: ${{ matrix.experimental }}
      runs-on: ${{ matrix.runs-on }}
      mongo-version: 6
    secrets:
      github-token: ${{ secrets._ORG_GITHUB_TOKEN }}
